import http from "node:http";
import { readFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
const dir=dirname(fileURLToPath(import.meta.url)), port=Number(process.env.PORT||3000);
const envKeys=["MODEL_ID","MODEL_NAME","OPENAI_MODEL","ANTHROPIC_MODEL","AZURE_OPENAI_DEPLOYMENT","GOOGLE_MODEL","GEMINI_MODEL","IDENTITY_PROBE_MODEL","DECLARED_MODEL_NAME","RUNTIME_DEPLOYMENT_LABEL","OPENAI_BASE_URL"];
const tools=[
{name:"probe_current_runtime",description:"Read exposed non-secret process metadata; cannot inspect the hidden model serving the MCP client.",inputSchema:{type:"object",properties:{},additionalProperties:false}},
{name:"probe_provider_status",description:"Check provider probe configuration without making a network request.",inputSchema:{type:"object",properties:{},additionalProperties:false}},
{name:"probe_provider",description:"Make one minimal request to configured OpenAI-compatible API and report response model metadata for that request only.",inputSchema:{type:"object",properties:{},additionalProperties:false}},
{name:"compare_identity_claims",description:"Compare claimed model name and provider-returned ID by exact string equality only.",inputSchema:{type:"object",properties:{claimed_name:{type:"string",minLength:1,maxLength:200},provider_returned_model_id:{type:"string",minLength:1,maxLength:200}},required:["claimed_name","provider_returned_model_id"],additionalProperties:false}}
];
const out=x=>({content:[{type:"text",text:JSON.stringify(x,null,2)}],structuredContent:x});
async function call(name,a={}){
if(name==="probe_current_runtime"){const e=Object.fromEntries(envKeys.filter(k=>process.env[k]?.trim()).map(k=>[k,process.env[k].trim()]));return out({status:Object.keys(e).length?"metadata_exposed_unverified":"identity_not_exposed",observed_at:new Date().toISOString(),runtime:{node:process.version,platform:process.platform},exposed_metadata:e,limits:["Labels are not independently verified.","This service cannot inspect ChatGPT or another client's hidden model state.","Secret environment variables are never returned."]})}
if(name==="probe_provider_status")return out({status:process.env.PROBE_API_KEY&&process.env.PROBE_MODEL_ID?"configured":"not_configured",required:["PROBE_API_KEY","PROBE_MODEL_ID"],optional:["PROBE_BASE_URL"],note:"No request made by status check."});
if(name==="compare_identity_claims"){const x=String(a.claimed_name||"").trim(),y=String(a.provider_returned_model_id||"").trim();if(!x||!y)return out({status:"invalid_input"});return out({status:x===y?"exact_string_match":"mismatch_or_alias",claimed_name:x,provider_returned_model_id:y,conclusion:"String comparison only; aliases are not inferred."})}
if(name==="probe_provider"){const key=process.env.PROBE_API_KEY,model=process.env.PROBE_MODEL_ID;if(!key||!model)return out({status:"not_configured",required:["PROBE_API_KEY","PROBE_MODEL_ID"],network_request_made:false});const base=(process.env.PROBE_BASE_URL||"https://api.openai.com/v1").replace(/\/+$/,"");let u;try{u=new URL(base)}catch{return out({status:"configuration_error",network_request_made:false})}if(u.protocol!=="https:"&&u.hostname!=="localhost"&&u.hostname!=="127.0.0.1")return out({status:"configuration_error",error:"HTTPS required for remote providers."});const t=Date.now();let r;try{r=await fetch(base+"/chat/completions",{method:"POST",headers:{Authorization:"Bearer "+key,"Content-Type":"application/json"},body:JSON.stringify({model,messages:[{role:"user",content:"Reply with the single word: OK"}],max_tokens:3,temperature:0}),signal:AbortSignal.timeout(20000)})}catch{return out({status:"request_failed",elapsed_ms:Date.now()-t})}let d;try{d=await r.json()}catch{d={}}if(!r.ok)return out({status:"provider_error",http_status:r.status,error:String(d?.error?.message||"Provider request failed").slice(0,300)});return out({status:d.model?"provider_response_metadata_received":"response_missing_model_id",requested_model:model,returned_model_id:d.model||null,response_id:d.id||null,system_fingerprint:d.system_fingerprint||null,elapsed_ms:Date.now()-t,scope:"This response identifies only this API request; not the hidden model of the calling client."})}
return null}
const json=(res,status,x)=>{res.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store","access-control-allow-origin":"*","access-control-allow-methods":"GET,POST,OPTIONS","access-control-allow-headers":"Content-Type,Accept,MCP-Protocol-Version"});res.end(JSON.stringify(x))};
http.createServer(async(req,res)=>{const path=new URL(req.url,"http://localhost").pathname;if(req.method==="OPTIONS"){res.writeHead(204,{"access-control-allow-origin":"*","access-control-allow-methods":"GET,POST,OPTIONS","access-control-allow-headers":"Content-Type,Accept,MCP-Protocol-Version"});return res.end()}if(path==="/health")return json(res,200,{name:"model-identity-probe",status:"online",calling_client_identity:"not_observable"});if(path==="/"&&req.method==="GET"){try{res.writeHead(200,{"content-type":"text/html; charset=utf-8","cache-control":"no-store"});return res.end(await readFile(join(dir,"public","index.html")))}catch{return json(res,500,{error:"UI missing"})}}if(path!=="/api/mcp")return json(res,404,{error:"Not found"});if(req.method==="GET")return json(res,200,{name:"model-identity-probe",version:"1.0.0",status:"online",transport:"stateless JSON-RPC over HTTP"});if(req.method!=="POST")return json(res,405,{error:"Method not allowed"});let raw="";for await(const c of req){raw+=c;if(raw.length>65536)return json(res,413,{error:"Request too large"})}let b;try{b=JSON.parse(raw)}catch{return json(res,400,{jsonrpc:"2.0",id:null,error:{code:-32700,message:"Parse error"}})}const id=b.id??null,send=(x,s=200)=>json(res,s,{jsonrpc:"2.0",id,...x});if(b.jsonrpc!=="2.0"||typeof b.method!=="string")return send({error:{code:-32600,message:"Invalid request"}},400);if(b.method.startsWith("notifications/")){res.writeHead(202);return res.end()}if(b.method==="initialize")return send({result:{protocolVersion:b.params?.protocolVersion||"2025-03-26",capabilities:{tools:{}},serverInfo:{name:"model-identity-probe",version:"1.0.0"}}});if(b.method==="ping")return send({result:{}});if(b.method==="tools/list")return send({result:{tools}});if(b.method==="tools/call"){try{const r=await call(b.params?.name,b.params?.arguments||{});return r?send({result:r}):send({error:{code:-32602,message:"Unknown tool"}},400)}catch{return send({error:{code:-32603,message:"Probe failed; sensitive details omitted"}},500)}}return send({error:{code:-32601,message:"Method not found"}},404)}).listen(port,"0.0.0.0",()=>console.log("Model Identity Probe listening on "+port));
