import {build} from "esbuild";
import {readFile,writeFile} from "node:fs/promises";
const result=await build({entryPoints:["apps/proofttl-card.js"],bundle:true,write:false,platform:"browser",format:"iife",target:"es2022",minify:true,metafile:true});
const script=result.outputFiles[0].text.replace(/<\/script/gi,"<\\/script");
const template=await readFile("apps/proofttl-card.html","utf8");
if(!template.includes("<!--PROOFTTL_CARD_SCRIPT-->"))throw new Error("Missing card script marker");
const html=template.replace("<!--PROOFTTL_CARD_SCRIPT-->","<script>"+script+"</script>");
await writeFile("apps/proofttl-card-resource.js","// Generated by npm run build:apps; no tenant data.\nexport const AUDIT_CARD_HTML = "+JSON.stringify(html)+";\n");
console.log("Built static bundled MCP Apps resource",Buffer.byteLength(html),"bytes");
